name: exam_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.4
  equatable: ^2.0.7
  cloud_firestore: ^5.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/images/


  fonts:
    - family: Sen

      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800
