// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKSa40KWayCjkIdhnenNUgL53URwb5ww',
    appId: '1:625404634105:web:026d69b0ba9f27e2e85328',
    messagingSenderId: '625404634105',
    projectId: 'imtihon-4-6bd7a',
    authDomain: 'imtihon-4-6bd7a.firebaseapp.com',
    storageBucket: 'imtihon-4-6bd7a.firebasestorage.app',
    measurementId: 'G-HKH2J5PH2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfk5z6KFOtURUw1YDxJ1lAqkyqdV0riMM',
    appId: '1:625404634105:android:edce192734bf445ae85328',
    messagingSenderId: '625404634105',
    projectId: 'imtihon-4-6bd7a',
    storageBucket: 'imtihon-4-6bd7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLxJfp59fwEZgwDdNzr2mIdCcZDYQXCg0',
    appId: '1:625404634105:ios:45a5be5414deacb7e85328',
    messagingSenderId: '625404634105',
    projectId: 'imtihon-4-6bd7a',
    storageBucket: 'imtihon-4-6bd7a.firebasestorage.app',
    iosBundleId: 'com.example.exam4',
  );

}